name: Release to Marketplace
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: "package.json"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install vsce
        run: yarn global add vsce

      - name: Install dependencies
        run: yarn install

      - name: package.jsonの`$.version`を書き換える
        run: |
          echo "version: ${{ github.ref_name }}"
          cat <<< $(jq  '.version = "${{ github.ref_name }}"' package.json) 1<> package.json

      - name: Build
        run: vsce package --yarn

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: extension
          path: "*.vsix"

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Download artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1

      - name: Install vsce
        run: yarn global add vsce

      - name: Publish
        run: vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
